### ISSUE TITLE
Module build failed: Error: Couldn't find preset "es2015"

### ISSUE THREAD

**Issue by renatodolce** [pablohpsilva/vue-material-boilerplate#1]
Olá Pablo, tudo bem? Espero que sim 😄 
Fiz o init, install e dps run dev, ai da esse erro:
![image](https://user-images.githubusercontent.com/5089350/31907834-c17a0456-b813-11e7-8e60-308b176c09a4.png)
no navegador acessando localhost:8080:
Cannot GET /

**Comment by renatodolce** [comment]
Consegui arrumar, removi o es2015 do presets de dentro do .babelrc localizado na /
![image](https://user-images.githubusercontent.com/5089350/31908788-c45f156e-b816-11e7-8190-2c23f30ea655.png)
Porém não sei se foi certo, poderia dar um feedback?? Obrigado!

**Comment by renatodolce** [comment]
@pablohpsilva Depois q meu app tava rodando legal, vi que tava desatualizado os módulos, ai fiz uma cópia do meu App e fiz o update e parou de funcionar meu app 😭  ai tive q corrigir vários padrões por causa do eslint, ate ai beleza, fui la e corrigi, mas mesmo assim minha div#app ta vazia, por favor poderia me ajudar?

**Comment by renatodolce** [comment]
Consegui arrumar dnv kkkk tive q comenta o import do modulo Toast.js

**Comment by pablohpsilva** [comment]
Para o erro do es2015:
```
yarn add --dev babel-preset-es2015
```

Sobre atualizar o linter e os pacotes eu fiz isso a alguns dias hehehe... vou subir as correcoes ASAP.
Obrigado!

**Comment by renatodolce** [comment]
Ok, depois irei fazer esse add
Quando eu disse q tinha atualizado meu app foi pq vi q vc atualizou tbm ai fiz no meu, foi ai q deu a 💩  mas agora ta funcionando 😄

**Comment by pablohpsilva** [comment]
Corrigido e template atualizado.

Valeu demais @renatodolce :D
